### ISSUE TITLE
Can't contribute, "bad option"

### ISSUE THREAD

**Issue by ffMathy** [kgajera/stripe-onboarder#5]
I tried forking the repo to fix #4 and #3 myself, but I can't run the tests. I already installed dependencies using `npm i`.

Here's the output I receive, with exit code 9.

```
C:\stripe-onboarder>npm test

> stripe-onboarder@1.0.3 test
> node --loader tsx --test test/onboard.ts

node: bad option: --test
```

**Comment by kgajera** [comment]
Hi @ffMathy! The tests are using [Node's test runner](https://nodejs.org/docs/latest-v18.x/api/test.html) which requires Node 18.

**Comment by ffMathy** [comment]
Awesome. Would be cool to document this somewhere.

**Comment by ffMathy** [comment]
Added this to documentation in #6.
